# Generated by Django 2.1.7 on 2019-04-25 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Score',
        ),
    ]
