# Generated by Django 2.1.7 on 2019-04-26 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0002_delete_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='time',
            field=models.FloatField(default=0),
        ),
    ]
